version: '3'
services:
  practice-docker:
    image: practice-docker:1.0
    depends_on:
      - mongodb
      - mongo-express
    ports:
      - 3000:3000
    networks:
      - practice-docker-network

  mongodb:
    image: mongo:6.0.6
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    networks:
      - practice-docker-network
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express:1.0.0-alpha.4
    depends_on:
      - mongodb
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
    networks:
      - practice-docker-network

networks:
  practice-docker-network:

volumes:
  mongo-data:
    driver: local

